<a href="https://colab.research.google.com/github/Ace1811/Data-Science---Standard-Projects/blob/master/Standard_Project_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install praw

Requirement already satisfied: praw in /usr/local/lib/python3.10/dist-packages (7.7.1)
Requirement already satisfied: prawcore<3,>=2.1 in /usr/local/lib/python3.10/dist-packages (from praw) (2.3.0)
Requirement already satisfied: update-checker>=0.18 in /usr/local/lib/python3.10/dist-packages (from praw) (0.18.0)
Requirement already satisfied: websocket-client>=0.54.0 in /usr/local/lib/python3.10/dist-packages (from praw) (1.6.2)
Requirement already satisfied: requests<3.0,>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from prawcore<3,>=2.1->praw) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw) (2023.7.22)

In [ ]:
#importirame pandas
import pandas as pd

In [ ]:
microsoft_stock_daily=pd.read_csv('/content/MSFT_Daily.csv') #gi chitame mnozhestvata so pomosh na pandas
microsoft_stock_weekly=pd.read_csv('/content/MSFT_weekly.csv')
microsoft_stock_monthly=pd.read_csv('/content/MSFT_monthly.csv')

In [ ]:
microsoft_stock_daily #microsoft stocks simnati od yahoo finance (dnevno nivo)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-09-19,113.050003,113.320000,111.040001,111.699997,105.828094,21728400
1,2018-09-20,112.279999,113.800003,111.930000,113.570000,107.599800,23714500
2,2018-09-21,114.000000,115.290001,113.510002,114.260002,108.253540,71229700
3,2018-09-24,113.029999,114.900002,112.220001,114.669998,108.641968,27334500
4,2018-09-25,114.800003,115.099998,113.750000,114.449997,108.433533,22668000
...,...,...,...,...,...,...,...
1252,2023-09-12,335.820007,336.790009,331.480011,331.769989,331.769989,17565500
1253,2023-09-13,331.309998,336.850006,331.170013,336.059998,336.059998,16544400
1254,2023-09-14,339.149994,340.859985,336.570007,338.700012,338.700012,20267000
1255,2023-09-15,336.920013,337.399994,329.649994,330.220001,330.220001,37666900
1256,2023-09-18,327.799988,330.399994,326.359985,329.059998,329.059998,16834200

In [ ]:
microsoft_stock_weekly #microsoft stocks simnati od yahoo finance (nedelno nivo)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-09-17,112.190002,115.290001,111.040001,114.260002,108.253532,138843500
1,2018-09-24,113.029999,115.099998,112.220001,114.370003,108.357735,110093600
2,2018-10-01,114.750000,116.180000,110.639999,112.129997,106.235489,120208900
3,2018-10-08,111.660004,113.080002,104.199997,109.570000,103.810089,228861900
4,2018-10-15,108.910004,111.809998,106.949997,108.660004,102.947929,155518200
...,...,...,...,...,...,...,...
257,2023-08-21,317.929993,332.980011,317.040009,322.980011,322.980011,106273900
258,2023-08-28,325.660004,331.989990,321.720001,328.660004,328.660004,90657400
259,2023-09-04,329.000000,336.160004,328.660004,334.269989,334.269989,74000800
260,2023-09-11,337.239990,340.859985,329.649994,330.220001,330.220001,108627100
261,2023-09-18,327.799988,330.399994,326.359985,329.059998,329.059998,16834200

In [ ]:
microsoft_stock_monthly   #microsoft stocks simnati od yahoo finance (mesechno nivo)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-10-01,114.750000,116.180000,100.110001,106.809998,101.195168,927548000
1,2018-11-01,107.050003,112.239998,99.349998,110.889999,105.060684,720228600
2,2018-12-01,113.000000,113.419998,93.959999,101.570000,96.646355,944314600
3,2019-01-01,99.550003,107.900002,97.199997,104.430000,99.367722,714212800
4,2019-02-01,103.779999,113.239998,102.349998,112.029999,106.599274,469095900
5,2019-03-01,112.889999,120.820000,108.800003,117.940002,112.702072,589095800
6,2019-04-01,118.949997,131.369995,118.099998,130.600006,124.799820,433157700
7,2019-05-01,130.529999,130.649994,123.040001,123.680000,118.187149,547218800
8,2019-06-01,123.849998,138.399994,119.010002,133.960007,128.484436,508324300
9,2019-07-01,136.630005,141.679993,134.669998,136.270004,130.700012,484079900
10,2019-08-01,137.000000,140.940002,130.779999,137.860001,132.225021,584482000
11,2019-09-01,136.610001,142.369995,134.509995,139.029999,133.791275,472544800
12,2019-10-01,139.660004,145.669998,133.220001,143.369995,137.967712,549523400
13,2019-11-01,144.259995,152.500000,142.970001,151.380005,145.675888,392371800
14,2019-12-01,151.809998,159.550003,146.649994,157.699997,152.274170,450303300
15,2020-01-01,158.779999,174.050003,156.509995,170.229996,164.372986,558530000
16,2020-02-01,170.429993,190.699997,152.000000,162.009995,156.435867,887522300
17,2020-03-01,165.309998,175.000000,132.520004,157.710007,152.699738,1612695500
18,2020-04-01,153.000000,180.399994,150.360001,179.210007,173.516708,984705000
19,2020-05-01,175.800003,187.509995,173.800003,183.250000,177.428360,688845000
20,2020-06-01,182.539993,204.399994,181.350006,203.509995,197.593521,764965400
21,2020-07-01,203.139999,216.380005,197.509995,205.009995,199.049866,770190800
22,2020-08-01,211.520004,231.149994,203.139999,225.529999,218.973343,692423900
23,2020-09-01,225.509995,232.860001,196.250000,210.330002,204.708923,768176300
24,2020-10-01,213.490005,225.210007,199.619995,202.470001,197.058945,631618000
25,2020-11-01,204.289993,228.119995,200.119995,214.070007,208.348969,573443000
26,2020-12-01,214.509995,227.179993,209.110001,222.419998,217.042526,594761700
27,2021-01-01,222.529999,242.639999,211.940002,231.960007,226.351913,648076400
28,2021-02-01,235.059998,246.130005,227.880005,232.380005,226.761734,490962200
29,2021-03-01,235.899994,241.050003,224.259995,235.770004,230.599655,724945800
30,2021-04-01,238.470001,263.190002,238.050003,252.179993,246.649796,568661600
31,2021-05-01,253.399994,254.350006,238.070007,249.679993,244.204620,495084900
32,2021-06-01,251.229996,271.649994,243.000000,270.899994,265.571045,508572200
33,2021-07-01,269.609985,290.149994,269.600006,284.910004,279.305542,522672700
34,2021-08-01,286.359985,305.839996,283.739990,301.880005,295.941681,441308900
35,2021-09-01,302.869995,305.320007,281.619995,281.920013,276.903412,502918700
36,2021-10-01,282.119995,332.000000,280.250000,331.619995,325.719055,516515800
37,2021-11-01,331.359985,349.670013,326.369995,330.589996,324.707397,509885200
38,2021-12-01,335.130005,344.299988,317.250000,336.320007,330.939728,625674800
39,2022-01-01,335.350006,338.000000,276.049988,310.980011,306.005157,947531400
40,2022-02-01,310.410004,315.119995,271.519989,298.790009,294.010132,697050600
41,2022-03-01,296.399994,315.950012,270.000000,308.309998,304.005096,734334200
42,2022-04-01,309.369995,315.109985,270.000000,277.519989,273.645050,627343400
43,2022-05-01,277.709991,290.880005,246.440002,271.869995,268.073944,742902000
44,2022-06-01,275.200012,277.690002,241.509995,256.829987,253.833771,621372300
45,2022-07-01,256.390015,282.000000,245.940002,280.739990,277.464813,534891800
46,2022-08-01,277.820007,294.179993,260.660004,261.470001,258.419647,477157600
47,2022-09-01,258.869995,267.450012,232.729996,232.899994,230.671524,575586600
48,2022-10-01,235.410004,251.039993,219.130005,232.130005,229.908905,671225100
49,2022-11-01,234.600006,255.330002,213.429993,255.139999,252.698715,615296000
50,2022-12-01,253.869995,263.920013,233.869995,239.820007,238.194717,591358700
51,2023-01-01,243.080002,249.830002,219.350006,247.809998,246.130554,666168100
52,2023-02-01,248.000000,276.760010,245.470001,249.419998,247.729645,615501000
53,2023-03-01,250.759995,289.269989,245.610001,288.299988,287.063324,747635000
54,2023-04-01,286.519989,308.929993,275.369995,307.260010,305.942047,551497100
55,2023-05-01,306.970001,335.940002,303.399994,328.390015,326.981415,600807200
56,2023-06-01,325.929993,351.470001,322.500000,340.540009,339.820526,547588700
57,2023-07-01,339.190002,366.779999,327.000000,335.920013,335.210297,666764400
58,2023-08-01,335.190002,338.540009,311.549988,327.760010,327.067535,479456700
59,2023-09-01,331.309998,340.859985,326.359985,329.059998,329.059998,214385200

In [ ]:
from datetime import datetime as dt  #so ovoj poseben kod simnuvame ESG score od microsoft na mesecno nivo
import urllib.request
import json
dataframes = []

url = "https://query2.finance.yahoo.com/v1/finance/esgChart?symbol=MSFT"  #linkot od kadeshto mozhe da simneme

connection = urllib.request.urlopen(url)

data = connection.read()
data_2 = json.loads(data)
Formatdata = data_2["esgChart"]["result"][0]["symbolSeries"]
Esg_score_monthly = pd.DataFrame(Formatdata) #pravime format na datata so pandas
Esg_score_monthly
Esg_score_monthly["timestamp"] = pd.to_datetime(Esg_score_monthly["timestamp"], unit="s") #od string datumi vo vistinski datumi format gi menuvame



# do ovoj datum sakame da ni bide mnozhestvoto
cutoff_date = pd.to_datetime('2018-09-17')

# Transpose the DataFrame to work with columns
Esg_score_monthly = Esg_score_monthly.transpose()

# Identify columns where the 'date' is higher than the cutoff date -> ako ni e povekje od toj datum da se dropne
columns_to_drop = Esg_score_monthly.columns[Esg_score_monthly.loc['timestamp'] < cutoff_date]

# Drop the identified columns from the DataFrame (transposed)
Esg_score_monthly = Esg_score_monthly.drop(columns=columns_to_drop)

# Transpose the DataFrame back to the original format
Esg_score_monthly = Esg_score_monthly.transpose()
Esg_score_monthly.reset_index(drop=True, inplace=True)
Esg_score_monthly = Esg_score_monthly.infer_objects()  # Ensure columns have appropriate data types

Esg_score_monthly #datasetot na mesecno nivo, no falat nekoi podatoci

    timestamp esgScore governanceScore environmentScore socialScore
0  2018-10-01    73.92           71.35            80.83       70.74
1  2018-11-01    74.15           70.15             82.5       70.81
2  2018-12-01    74.15           70.15             82.5       70.81
3  2019-01-01    74.15           70.15             82.5       70.81
4  2019-02-01    74.15           70.15             82.5       70.81
5  2019-03-01    74.15           70.15             82.5       70.81
6  2019-04-01    74.15           70.15             82.5       70.81
7  2019-05-01    74.15           70.15             82.5       70.81
8  2019-06-01    74.15           70.15             82.5       70.81
9  2019-07-01    74.55           70.15            83.83       70.81
10 2019-08-01    74.55           70.15            83.83       70.81
11 2019-09-01    74.65           70.15            84.17       70.81
12 2019-10-01    74.65           70.15            84.17       70.81
13 2019-11-01     74.8           70.75            84.17       70.81
14 2019-12-01    15.35            5.19             0.44        9.71
15 2020-01-01    15.35            5.19             0.44        9.71
16 2020-02-01    15.35            5.19             0.44        9.71
17 2020-03-01    15.55            5.24             0.44        9.87
18 2020-04-01      NaT             NaT              NaT         NaT
19 2020-05-01      NaT             NaT              NaT         NaT
20 2020-06-01      NaT             NaT              NaT         NaT
21 2020-07-01    14.91            5.07             0.47        9.37
22 2020-08-01    14.91            5.07             0.47        9.37
23 2020-09-01      NaT             NaT              NaT         NaT
24 2020-10-01    14.94            5.09             0.47        9.37
25 2020-11-01      NaT             NaT              NaT         NaT
26 2020-12-01      NaT             NaT              NaT         NaT
27 2021-01-01    14.74             4.9             0.47        9.37
28 2021-02-01    14.74             4.9             0.47        9.37
29 2021-03-01    14.74             4.9             0.47        9.37
30 2021-04-01      NaT             NaT              NaT         NaT
31 2021-05-01    14.63            4.83             0.42        9.37
32 2021-06-01      NaT             NaT              NaT         NaT
33 2021-07-01      NaT             NaT              NaT         NaT
34 2021-08-01      NaT             NaT              NaT         NaT
35 2021-09-01    13.26            4.73             0.46        8.06
36 2021-10-01      NaT             NaT              NaT         NaT
37 2021-11-01      NaT             NaT              NaT         NaT
38 2021-12-01      NaT             NaT              NaT         NaT
39 2022-01-01      NaT             NaT              NaT         NaT
40 2022-02-01    13.26            4.73             0.46        8.06
41 2022-03-01      NaT             NaT              NaT         NaT
42 2022-04-01      NaT             NaT              NaT         NaT
43 2022-05-01    13.75            5.23             0.46        8.06
44 2022-06-01      NaT             NaT              NaT         NaT
45 2022-07-01      NaT             NaT              NaT         NaT
46 2022-08-01    15.24            5.33             1.53        8.39

In [ ]:
Esg_score_monthly.interpolate(method='ffill', order=2, inplace=True) #pravime dodavanje na mestata kadeshto fali data

In [ ]:
Esg_score_monthly #dodadena data

    timestamp  esgScore  governanceScore  environmentScore  socialScore
0  2018-10-01     73.92            71.35             80.83        70.74
1  2018-11-01     74.15            70.15             82.50        70.81
2  2018-12-01     74.15            70.15             82.50        70.81
3  2019-01-01     74.15            70.15             82.50        70.81
4  2019-02-01     74.15            70.15             82.50        70.81
5  2019-03-01     74.15            70.15             82.50        70.81
6  2019-04-01     74.15            70.15             82.50        70.81
7  2019-05-01     74.15            70.15             82.50        70.81
8  2019-06-01     74.15            70.15             82.50        70.81
9  2019-07-01     74.55            70.15             83.83        70.81
10 2019-08-01     74.55            70.15             83.83        70.81
11 2019-09-01     74.65            70.15             84.17        70.81
12 2019-10-01     74.65            70.15             84.17        70.81
13 2019-11-01     74.80            70.75             84.17        70.81
14 2019-12-01     15.35             5.19              0.44         9.71
15 2020-01-01     15.35             5.19              0.44         9.71
16 2020-02-01     15.35             5.19              0.44         9.71
17 2020-03-01     15.55             5.24              0.44         9.87
18 2020-04-01     15.55             5.24              0.44         9.87
19 2020-05-01     15.55             5.24              0.44         9.87
20 2020-06-01     15.55             5.24              0.44         9.87
21 2020-07-01     14.91             5.07              0.47         9.37
22 2020-08-01     14.91             5.07              0.47         9.37
23 2020-09-01     14.91             5.07              0.47         9.37
24 2020-10-01     14.94             5.09              0.47         9.37
25 2020-11-01     14.94             5.09              0.47         9.37
26 2020-12-01     14.94             5.09              0.47         9.37
27 2021-01-01     14.74             4.90              0.47         9.37
28 2021-02-01     14.74             4.90              0.47         9.37
29 2021-03-01     14.74             4.90              0.47         9.37
30 2021-04-01     14.74             4.90              0.47         9.37
31 2021-05-01     14.63             4.83              0.42         9.37
32 2021-06-01     14.63             4.83              0.42         9.37
33 2021-07-01     14.63             4.83              0.42         9.37
34 2021-08-01     14.63             4.83              0.42         9.37
35 2021-09-01     13.26             4.73              0.46         8.06
36 2021-10-01     13.26             4.73              0.46         8.06
37 2021-11-01     13.26             4.73              0.46         8.06
38 2021-12-01     13.26             4.73              0.46         8.06
39 2022-01-01     13.26             4.73              0.46         8.06
40 2022-02-01     13.26             4.73              0.46         8.06
41 2022-03-01     13.26             4.73              0.46         8.06
42 2022-04-01     13.26             4.73              0.46         8.06
43 2022-05-01     13.75             5.23              0.46         8.06
44 2022-06-01     13.75             5.23              0.46         8.06
45 2022-07-01     13.75             5.23              0.46         8.06
46 2022-08-01     15.24             5.33              1.53         8.39

In [ ]:
#make daily dataset --> pravime dataset na dnevno nivo od prethodnoto so toa shto go proshiruvame datasetot
#i potoa kje gi fillnuvame podatocite
start_date = Esg_score_monthly['timestamp'].min()
end_date = Esg_score_monthly['timestamp'].max()
daily_date_range = pd.date_range(start_date, end_date, freq='D')
Esg_score_daily = pd.DataFrame({'timestamp': daily_date_range})
Esg_score_daily = Esg_score_daily.merge(Esg_score_monthly, on='timestamp', how='left')

In [ ]:
Esg_score_daily

      timestamp  esgScore  governanceScore  environmentScore  socialScore
0    2018-10-01     73.92            71.35             80.83        70.74
1    2018-10-02       NaN              NaN               NaN          NaN
2    2018-10-03       NaN              NaN               NaN          NaN
3    2018-10-04       NaN              NaN               NaN          NaN
4    2018-10-05       NaN              NaN               NaN          NaN
...         ...       ...              ...               ...          ...
1396 2022-07-28       NaN              NaN               NaN          NaN
1397 2022-07-29       NaN              NaN               NaN          NaN
1398 2022-07-30       NaN              NaN               NaN          NaN
1399 2022-07-31       NaN              NaN               NaN          NaN
1400 2022-08-01     15.24             5.33              1.53         8.39

[1401 rows x 5 columns]

In [ ]:
Esg_score_daily.set_index('timestamp', inplace=True)  # Set the date column as the index
Esg_score_daily = Esg_score_daily.resample('D').asfreq()  # Resample to daily frequency
Esg_score_daily.interpolate(method='time', inplace=True) #gi filnuvame podatocite vremenski

In [ ]:
Esg_score_daily.reset_index(inplace=True)

In [ ]:
Esg_score_daily #finalnoto podatocno mnozestvo bez missing values

      timestamp   esgScore  governanceScore  environmentScore  socialScore
0    2018-10-01  73.920000        71.350000         80.830000    70.740000
1    2018-10-02  73.927419        71.311290         80.883871    70.742258
2    2018-10-03  73.934839        71.272581         80.937742    70.744516
3    2018-10-04  73.942258        71.233871         80.991613    70.746774
4    2018-10-05  73.949677        71.195161         81.045484    70.749032
...         ...        ...              ...               ...          ...
1396 2022-07-28  15.047742         5.317097          1.391935     8.347419
1397 2022-07-29  15.095806         5.320323          1.426452     8.358065
1398 2022-07-30  15.143871         5.323548          1.460968     8.368710
1399 2022-07-31  15.191935         5.326774          1.495484     8.379355
1400 2022-08-01  15.240000         5.330000          1.530000     8.390000

[1401 rows x 5 columns]

In [ ]:
#make weekly dataset
#tuka pravime nedelen dataset na istiot nachin kako dnevniot

weekly_date_range = pd.date_range(start_date, end_date, freq='W')
Esg_score_weekly = pd.DataFrame({'timestamp': weekly_date_range})
Esg_score_weekly = Esg_score_weekly.merge(Esg_score_daily, on='timestamp', how='left')
Esg_score_weekly

     timestamp   esgScore  governanceScore  environmentScore  socialScore
0   2018-10-07  73.964516        71.117742         81.153226    70.753548
1   2018-10-14  74.016452        70.846774         81.530323    70.769355
2   2018-10-21  74.068387        70.575806         81.907419    70.785161
3   2018-10-28  74.120323        70.304839         82.284516    70.800968
4   2018-11-04  74.150000        70.150000         82.500000    70.810000
..         ...        ...              ...               ...          ...
195 2022-07-03  13.846129         5.236452          0.529032     8.081290
196 2022-07-10  14.182581         5.259032          0.770645     8.155806
197 2022-07-17  14.519032         5.281613          1.012258     8.230323
198 2022-07-24  14.855484         5.304194          1.253871     8.304839
199 2022-07-31  15.191935         5.326774          1.495484     8.379355

[200 rows x 5 columns]

In [ ]:
Esg_score_daily.rename(columns={'timestamp': 'Date'}, inplace=True)
Esg_score_weekly.rename(columns={'timestamp': 'Date'}, inplace=True)
Esg_score_monthly.rename(columns={'timestamp': 'Date'}, inplace=True)
Esg_score_daily.columns #menuvame imeto na datum kolonata od timestamp vo Date za da se poklopuvaat so stocks mnozhestvata
# za da napravime merge

Index(['Date', 'esgScore', 'governanceScore', 'environmentScore',
       'socialScore'],
      dtype='object')

In [ ]:
Esg_score_daily['Date'] = pd.to_datetime(Esg_score_daily['Date'])
Esg_score_weekly['Date'] = pd.to_datetime(Esg_score_weekly['Date'])
Esg_score_monthly['Date'] = pd.to_datetime(Esg_score_monthly['Date'])

microsoft_stock_daily['Date'] = pd.to_datetime(microsoft_stock_daily['Date'])
microsoft_stock_weekly['Date'] = pd.to_datetime(microsoft_stock_weekly['Date'])
microsoft_stock_monthly['Date'] = pd.to_datetime(microsoft_stock_monthly['Date']) #na site mnozestva gi pravime datumite vo datetime

In [ ]:
merged_daily=merged_df = pd.merge(Esg_score_daily, microsoft_stock_daily, on='Date', how='inner')
merged_weekly=merged_df = pd.merge(Esg_score_weekly, microsoft_stock_weekly, on='Date', how='inner')
merged_monthly=merged_df = pd.merge(Esg_score_monthly, microsoft_stock_monthly, on='Date', how='inner')

merged_weekly = Esg_score_weekly.merge(microsoft_stock_weekly, left_index=True, right_index=True, how='inner')
merged_weekly = merged_weekly.drop(columns='Date_y') #tuka pravime merge

In [ ]:
merged_daily

In [ ]:

merged_weekly

In [ ]:
merged_monthly

In [ ]:
import praw  #alatkata za chitanje na reddit posts
import pandas as pd

reddit = praw.Reddit(client_id='jhZ3JT3g3xwZjUssf9J4iTVw',
                     client_secret='_er23Iebiujaisd0wMAQdZCx53967A',
                     user_agent='scraper 1.0 by /u/Ksenijapetrovska')

microsoft = reddit.subreddit('Microsoft')

# Retrieve posts from the subreddit
posts = Microsoft_subreddit.new(limit=200)  # Use the "new" method to retrieve new posts

# Create a list to store the post data
post_data = []

# Iterate over the posts and extract relevant information
for post in posts:
    post_data.append({
        'Title': post.title,
        'Post Score': post.score,
        'Author': post.author.name,
        'Post ID': post.id,
        'Subreddit': post.subreddit.display_name
    })

# Create a DataFrame from the post data
microsoft_posts = pd.DataFrame(post_data)

# Print the resulting DataFrame
print(microsoft_posts)

In [ ]:
microsoft_posts

                                               headline
0     My account was hacked, he changed the e-mail a...
1                                         Xbox Store(s)
2     Can someone please tell me how to turn the fin...
3     resetting Hp computer, back to factory settings ?
4              Minecraft Bedrock is Filled with Hackers
...                                                 ...
1396                       Windows 11 doesn’t shut down
1397     Is the XBOX GAME PASS trial not available now?
1398  Using Azure Key Vault to Access Client Secret ...
1399                                   MS Authenticator
1400  New ASUS Windows 11 PC-- Should I disable S Mode?

[1401 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split #za delenje podatochno mnozhestvo train 80% test 20%
from sklearn.preprocessing import LabelEncoder #label encoder za od tekst da se napravi vo brojki
from xgboost import XGBRegressor #za xgb regresija
from sklearn.metrics import mean_squared_error #za testiranje na modelot na regresijata

label_encoder = LabelEncoder() #enkodirame tekst vo brojki
microsoft_posts['headline'] = label_encoder.fit_transform(microsoft_posts['headline'])
microsoft_posts  #enkodiran datasetot od vestite

    headline  common_column
0         28              0
1         42              0
2          4              0
3         45              0
4         26              0
5         23              0
6         12              0
7         41              0
8          1              0
9         17              0
10        37              0
11        13              0
12        30              0
13        43              0
14        39              0
15        27              0
16        35              0
17        29              0
18        31              0
19        10              0
20        20              0
21         3              0
22         8              0
23         2              0
24         0              0
25        32              0
26        25              0
27         9              0
28        19              0
29        11              0
30        24              0
31        33              0
32        22              0
33         5              0
34        36              0
35        44              0
36        15              0
37        21              0
38         7              0
39        18              0
40        14              0
41         6              0
42        34              0
43        38              0
44        16              0
45        40              0
46        46              0

In [ ]:
# pravime merge od vestite i daily datasetot
min_length = min(len(merged_daily), len(microsoft_posts))

merged_daily = merged_daily.iloc[:min_length, :]
microsoft_posts = microsoft_posts.iloc[:min_length, :]

daily_final = pd.concat([merged_daily, microsoft_posts], axis=1)
daily_final

In [ ]:
# pravime merge od vestite i nedelno datasetot
min_length = min(len(merged_weekly), len(microsoft_posts))

merged_weekly = merged_weekly.iloc[:min_length, :]
microsoft_posts = microsoft_posts.iloc[:min_length, :]

weekly_final = pd.concat([merged_weekly, microsoft_posts], axis=1)
weekly_final

In [ ]:
# pravime merge od vestite i mesechno datasetot
min_length = min(len(merged_monthly), len(microsoft_posts))

merged_monthly = merged_monthly.iloc[:min_length, :]
microsoft_posts = microsoft_posts.iloc[:min_length, :]

monthly_final = pd.concat([merged_monthly, microsoft_posts], axis=1)
monthly_final

In [ ]:
weekly_final.rename(columns={'Date_x': 'Date'}, inplace=True)
weekly_final

In [ ]:
daily_final.drop(daily_final.columns[-1:], axis=1, inplace=True)
daily_final

In [ ]:
daily_final

,Date,esgScore,governanceScore,environmentScore,socialScore,Open,High,Low,Close,Adj Close,Volume,headline
0,2018-10-01,73.920000,71.350000,80.830000,70.740000,114.750000,115.680000,114.730003,115.610001,109.532562,18883100,28
1,2018-10-02,73.927419,71.311290,80.883871,70.742258,115.300003,115.839996,114.440002,115.150002,109.096741,20787200,42
2,2018-10-03,73.934839,71.272581,80.937742,70.744516,115.419998,116.180000,114.930000,115.169998,109.115692,16648000,4
3,2018-10-04,73.942258,71.233871,80.991613,70.746774,114.610001,114.760002,111.629997,112.790001,106.860809,34821700,45
4,2018-10-05,73.949677,71.195161,81.045484,70.749032,112.629997,113.169998,110.639999,112.129997,106.235504,29068900,26
5,2018-10-08,73.971935,71.079032,81.207097,70.755806,111.660004,112.029999,109.339996,110.849998,105.022774,29640600,23
6,2018-10-09,73.979355,71.040323,81.260968,70.758065,111.139999,113.080002,110.800003,112.260002,106.358681,26198600,12
7,2018-10-10,73.986774,71.001613,81.314839,70.760323,111.239998,111.500000,105.790001,106.160004,100.579315,61376300,41
8,2018-10-11,73.994194,70.962903,81.368710,70.762581,105.349998,108.930000,104.199997,105.910004,100.342476,63904300,1
9,2018-10-12,74.001613,70.924194,81.422581,70.764839,109.010002,111.239998,107.120003,109.570000,103.810074,47742100,17
10,2018-10-15,74.023871,70.808065,81.584194,70.771613,108.910004,109.480003,106.949997,107.599998,101.943619,32068100,37
11,2018-10-16,74.031290,70.769355,81.638065,70.773871,109.540001,111.410004,108.949997,111.000000,105.164894,31610200,13
12,2018-10-17,74.038710,70.730645,81.691935,70.776129,111.680000,111.809998,109.550003,110.709999,104.890137,26548200,30
13,2018-10-18,74.046129,70.691935,81.745806,70.778387,110.099998,110.529999,107.830002,108.500000,102.796333,32506200,43
14,2018-10-19,74.053548,70.653226,81.799677,70.780645,108.930000,110.860001,108.209999,108.660004,102.947922,32785500,39
15,2018-10-22,74.075806,70.537097,81.961290,70.787419,109.320000,110.540001,108.239998,109.629997,103.866913,26545600,27
16,2018-10-23,74.083226,70.498387,82.015161,70.789677,107.769997,108.970001,105.110001,108.099998,102.417351,43770400,35
17,2018-10-24,74.090645,70.459677,82.069032,70.791935,108.410004,108.489998,101.589996,102.320000,96.941185,63897800,29
18,2018-10-25,74.098065,70.420968,82.122903,70.794194,106.550003,109.269997,106.150002,108.300003,102.606834,61646800,31
19,2018-10-26,74.105484,70.382258,82.176774,70.796452,105.690002,108.750000,104.760002,106.959999,101.337288,55523100,10
20,2018-10-29,74.127742,70.266129,82.338387,70.803226,108.110001,108.699997,101.629997,103.849998,98.390755,55162000,20
21,2018-10-30,74.135161,70.227419,82.392258,70.805484,103.660004,104.379997,100.110001,103.730003,98.277092,65350900,3
22,2018-10-31,74.142581,70.188710,82.446129,70.807742,105.440002,108.139999,105.389999,106.809998,101.195175,51062400,8
23,2018-11-01,74.150000,70.150000,82.500000,70.810000,107.050003,107.320000,105.529999,105.919998,100.351936,33384200,2
24,2018-11-02,74.150000,70.150000,82.500000,70.810000,106.480003,107.320000,104.980003,106.160004,100.579315,37680200,0
25,2018-11-05,74.150000,70.150000,82.500000,70.810000,106.370003,107.739998,105.900002,107.510002,101.858345,27922100,32
26,2018-11-06,74.150000,70.150000,82.500000,70.810000,107.379997,108.839996,106.279999,107.720001,102.057312,24340200,25
27,2018-11-07,74.150000,70.150000,82.500000,70.810000,109.440002,112.239998,109.400002,111.959999,106.074432,37901700,9
28,2018-11-08,74.150000,70.150000,82.500000,70.810000,111.800003,112.209999,110.910004,111.750000,105.875473,25644100,19
29,2018-11-09,74.150000,70.150000,82.500000,70.810000,110.849998,111.449997,108.760002,109.570000,103.810074,32039200,11
30,2018-11-12,74.150000,70.150000,82.500000,70.810000,109.419998,109.959999,106.099998,106.870003,101.252007,33621800,24
31,2018-11-13,74.150000,70.150000,82.500000,70.810000,107.550003,108.739998,106.639999,106.940002,101.318329,35374600,33
32,2018-11-14,74.150000,70.150000,82.500000,70.810000,108.099998,108.260002,104.470001,104.970001,99.881508,39495100,22
33,2018-11-15,74.150000,70.150000,82.500000,70.810000,104.989998,107.800003,103.910004,107.279999,102.079552,38505200,5
34,2018-11-16,74.150000,70.150000,82.500000,70.810000,107.080002,108.879997,106.800003,108.290001,103.040596,33502100,36
35,2018-11-19,74.150000,70.150000,82.500000,70.810000,108.269997,108.559998,103.550003,104.620003,99.548508,44773900,44
36,2018-11-20,74.150000,70.150000,82.500000,70.810000,101.800003,102.970001,99.349998,101.709999,96.779556,64052500,15
37,2018-11-21,74.150000,70.150000,82.500000,70.810000,103.599998,104.430000,102.239998,103.110001,98.111687,28130600,21
38,2018-11-23,74.150000,70.150000,82.500000,70.810000,102.169998,103.809998,102.000000,103.070000,98.073647,13823100,7
39,2018-11-26,74.150000,70.150000,82.500000,70.810000,104.790001,106.629997,104.580002,106.470001,101.308823,32336200,18
40,2018-11-27,74.150000,70.150000,82.500000,70.810000,106.269997,107.330002,105.360001,107.139999,101.946320,29124500,14
41,2018-11-28,74.150000,70.150000,82.500000,70.810000,107.889999,111.330002,107.860001,111.120003,105.733398,46788500,6
42,2018-11-29,74.150000,70.150000,82.500000,70.810000,110.330002,111.120003,109.029999,110.190002,104.848503,28123200,34
43,2018-11-30,74.150000,70.150000,82.500000,70.810000,110.699997,110.970001,109.360001,110.889999,105.514557,33665600,38
44,2018-12-03,74.150000,70.150000,82.500000,70.810000,113.000000,113.419998,110.730003,112.089996,106.656387,34732800,16
45,2018-12-04,74.150000,70.150000,82.500000,70.810000,111.940002,112.639999,108.209999,108.519997,103.259445,45197000,40
46,2018-12-06,74.150000,70.150000,82.500000,70.810000,105.820000,109.239998,105.000000,109.190002,103.896980,49107400,46

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

In [ ]:
#sega kje napravime predikcija za dnevno nedelno i mesecno nivo

In [ ]:
#funkcija koja kje sluzhi za da predviduvame so xgb regressor. Ja pravime funkcijata za da predviduvame na 3te  datasets
#za da ne go pishuvame kodot 3 pati. Chitame dataset delima na X,Y trenirame, barame error i R^2
def XGB_reggresor(dataset):
  y=dataset['Open']
  dropcolumns=['Open','Date']
  x = dataset.drop(dropcolumns, axis=1)
  X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)
  model = XGBRegressor()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  mse = mean_squared_error(y_test, y_pred)

  mse = mean_squared_error(y_test, y_pred)


  rmse = np.sqrt(mse)


  mae = mean_absolute_error(y_test, y_pred)

  r_squared = r2_score(y_test, y_pred)

  print(f"Mean Squared Error: {mse}")
  print(f"Root Mean Squared Error: {rmse}")
  print(f"Mean Absolute Error: {mae}")
  print(f"R-squared: {r_squared}")

In [ ]:
XGB_reggresor(daily_final)

Mean Squared Error: 2.003338361095741
Root Mean Squared Error: 1.4153933591393388
Mean Absolute Error: 1.3200568575195306
R-squared: 0.7590391229191291

In [ ]:
XGB_reggresor(weekly_final) #Ova se rezultatite i bi trebalo na nedelno nivo da se najokej bez overfitting najverojatno?

Mean Squared Error: 5.735318525447454
Root Mean Squared Error: 2.394852505990182
Mean Absolute Error: 1.9628280132812492
R-squared: 0.9578525747616984

In [ ]:
XGB_reggresor(monthly_final)

Mean Squared Error: 308.21801774165993
Root Mean Squared Error: 17.55613903287565
Mean Absolute Error: 14.249701017382813
R-squared: 0.9206877754913358

In [ ]:

#linearna regresija

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
#isto kako prethodnata funkcija no sega samo za regresija
def lin_regr(dataset):
  y=dataset['Open']
  dropcolumns=['Open','Date']
  x = dataset.drop(dropcolumns, axis=1)
  X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)
  model = LinearRegression()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  mse = mean_squared_error(y_test, y_pred)
  rmse = mse**0.5
  r_squared = r2_score(y_test, y_pred)
  print(f"RMSE: {rmse}")
  print(f"R-squared: {r_squared}")

In [ ]:
lin_regr(daily_final)
lin_regr(weekly_final)
lin_regr(monthly_final)  #Ova se rezultatite i bi trebalo na nedelno nivo da se najokej bez overfitting valjda?

RMSE: 0.9228455769893696
R-squared: 0.8975645456109996
RMSE: 1.755181386689185
R-squared: 0.9773609855988403
RMSE: 10.189541761063655
R-squared: 0.97328277086912